# Generated by Django 3.1.4 on 2021-06-06 14:16

import _socket
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEntry',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True)),
                ('month', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('submitted_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='new', max_length=10)),
                ('monthly_overtime', models.IntegerField(default=0)),
                ('annual_leave_taken', models.IntegerField(default=0)),
                ('sick_leave_taken', models.IntegerField(default=0)),
                ('study_leave_taken', models.IntegerField(default=0)),
                ('compassionate_leave_taken', models.IntegerField(default=0)),
                ('maternity_leave_taken', models.IntegerField(default=0)),
                ('paternity_leave_taken', models.IntegerField(default=0)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('rejected_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bhp_personnel.employee')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bhp_personnel.supervisor')),
            ],
            options={
                'unique_together': {('month', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('entry_type', models.CharField(choices=[('RH', 'Regular hours'), ('H', 'Holiday'), ('SL', 'Sick Leave'), ('AL', 'Annual Leave'), ('FH', 'Feeding Hour'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('STL', 'Study Leave'), ('CL', 'Compassionate Leave'), ('WE', 'Weekend')], default='reg_hours', max_length=10)),
                ('day_indicator', models.BooleanField(blank=True, default=False, null=True)),
                ('feeding_hour', models.BooleanField(blank=True, default=False, null=True)),
                ('monthly_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheet.monthlyentry')),
            ],
            options={
                'unique_together': {('monthly_entry', 'day', 'entry_type')},
            },
        ),
    ]
